name: JavaScript Lint (Flat Config)

on:
  push:
    branches: main


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ESLint
        run: npm install -g eslint

      - name: Run ESLint
        run: eslint demo.js
